// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace WebMenagement_2.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240621013809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Content = "Voluptatum aut nihil illo camisi karşıdakine sit sed rem.",
                            PostId = 14,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 2,
                            Content = "Rem non bilgiyasayarı exercitationem non aliquam ipsum.",
                            PostId = 16,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 3,
                            Content = "İllo sed aperiam sunt eum consectetur dışarı dolorem dolayı.",
                            PostId = 9,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 4,
                            Content = "Ducimus açılmadan otobüs.",
                            PostId = 23,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 5,
                            Content = "Bilgiyasayarı aut olduğu bilgisayarı.",
                            PostId = 18,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 6,
                            Content = "İusto quam koyun vitae molestiae yapacakmış kulu.",
                            PostId = 16,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 7,
                            Content = "Voluptatem adresini sarmal göze sayfası layıkıyla.",
                            PostId = 20,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 8,
                            Content = "Kalemi gülüyorum patlıcan dışarı quia koşuyorlar aspernatur.",
                            PostId = 30,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 9,
                            Content = "Ad aut doloremque ekşili architecto gidecekmiş düşünüyor.",
                            PostId = 50,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 10,
                            Content = "Explicabo kutusu beğendim et nihil ona çünkü voluptatem.",
                            PostId = 14,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 11,
                            Content = "Masaya aliquid sokaklarda ki voluptas iusto incidunt.",
                            PostId = 3,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 12,
                            Content = "Makinesi öyle quia enim iusto.",
                            PostId = 18,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 13,
                            Content = "Corporis nisi eve ve sokaklarda dignissimos yapacakmış.",
                            PostId = 30,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 14,
                            Content = "Dışarı ona sed yazın aliquam çobanın çünkü.",
                            PostId = 49,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 15,
                            Content = "Magni aliquam sequi bundan sit ve quia ışık gitti amet.",
                            PostId = 31,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 16,
                            Content = "Dolayı adresini ötekinden domates eaque sıla eaque salladı bahar.",
                            PostId = 3,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 17,
                            Content = "Aspernatur dolores sequi adipisci değirmeni qui magni.",
                            PostId = 11,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 18,
                            Content = "Labore enim kapının.",
                            PostId = 31,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 19,
                            Content = "Cesurca batarya anlamsız kalemi voluptate aliquid eos laudantium consectetur voluptatem.",
                            PostId = 44,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 20,
                            Content = "İpsum çarpan iure sed in.",
                            PostId = 29,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 21,
                            Content = "Masanın camisi suscipit un sunt exercitationem eve.",
                            PostId = 26,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 22,
                            Content = "Dicta masanın sed mi quis explicabo.",
                            PostId = 7,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 23,
                            Content = "Consequatur sit inventore.",
                            PostId = 10,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 24,
                            Content = "Sed nihil voluptatem ullam aliquam hesap beğendim sayfası accusantium quia.",
                            PostId = 12,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 25,
                            Content = "Consequatur voluptatem beatae çakıl eaque sequi sit beğendim masanın.",
                            PostId = 22,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 26,
                            Content = "Dağılımı suscipit et teldeki ki nisi ki.",
                            PostId = 13,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 27,
                            Content = "Kapının ekşili eaque.",
                            PostId = 45,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 28,
                            Content = "Enim filmini nihil gördüm.",
                            PostId = 8,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 29,
                            Content = "Mutlu kapının koşuyorlar.",
                            PostId = 17,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 30,
                            Content = "Quia iure ducimus değirmeni ea ex laboriosam de.",
                            PostId = 21,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 31,
                            Content = "Ducimus ve sıla sevindi voluptatem beğendim odit.",
                            PostId = 9,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 32,
                            Content = "Duyulmamış hesap dolorem et magnam fugit.",
                            PostId = 36,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 33,
                            Content = "Doğru cesurca batarya vel.",
                            PostId = 30,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 34,
                            Content = "Beğendim dicta iusto çorba.",
                            PostId = 11,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 35,
                            Content = "Quae mutlu beğendim doloremque.",
                            PostId = 32,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 36,
                            Content = "Sit eius odio velit et minima çorba corporis filmini.",
                            PostId = 21,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 37,
                            Content = "Odio dağılımı aut sokaklarda velit sit nostrum koştum modi gazete.",
                            PostId = 2,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 38,
                            Content = "Adipisci et ekşili kapının blanditiis dignissimos iusto laudantium lambadaki okuma.",
                            PostId = 47,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 39,
                            Content = "Patlıcan dağılımı mutlu ipsum şafak tempora corporis masanın esse.",
                            PostId = 30,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 40,
                            Content = "İusto enim camisi voluptas inventore aut koştum quam bahar nemo.",
                            PostId = 41,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 41,
                            Content = "Masanın explicabo ama karşıdakine nisi.",
                            PostId = 5,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 42,
                            Content = "Ullam quia türemiş tempora için alias.",
                            PostId = 25,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 43,
                            Content = "Sit deleniti sed quis.",
                            PostId = 49,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 44,
                            Content = "Quasi ışık consequuntur.",
                            PostId = 46,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 45,
                            Content = "Düşünüyor ama velit uzattı.",
                            PostId = 26,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 46,
                            Content = "Sevindi iusto kutusu teldeki voluptatum quae odio salladı eaque enim.",
                            PostId = 18,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 47,
                            Content = "Mi iusto uzattı patlıcan ama şafak nihil nisi.",
                            PostId = 47,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 48,
                            Content = "Çıktılar sequi balıkhaneye sit mıknatıslı tempora sit patlıcan consequatur.",
                            PostId = 14,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 49,
                            Content = "Enim qui quae mıknatıslı salladı suscipit quae nesciunt voluptatem.",
                            PostId = 24,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 50,
                            Content = "Çorba aut dicta dignissimos ut.",
                            PostId = 21,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 51,
                            Content = "İllo alias velit patlıcan gazete voluptatem aut enim gördüm dışarı.",
                            PostId = 13,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 52,
                            Content = "Voluptatem molestiae teldeki autem türemiş filmini.",
                            PostId = 44,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 53,
                            Content = "Cesurca sed düşünüyor bilgiyasayarı olduğu cesurca quam consequatur.",
                            PostId = 38,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 54,
                            Content = "Beğendim odio koştum patlıcan koyun.",
                            PostId = 42,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 55,
                            Content = "Aliquam architecto ut.",
                            PostId = 38,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 56,
                            Content = "Consectetur sandalye ötekinden şafak gülüyorum.",
                            PostId = 17,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 57,
                            Content = "Eius çarpan ea.",
                            PostId = 44,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 58,
                            Content = "Dolorem esse doğru sit ea gülüyorum quia olduğu.",
                            PostId = 50,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 59,
                            Content = "Aliquid sıfat gördüm consequatur fugit gidecekmiş veniam explicabo veritatis öyle.",
                            PostId = 49,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 60,
                            Content = "Velit adanaya sit.",
                            PostId = 36,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 61,
                            Content = "Magni koyun orta değirmeni düşünüyor.",
                            PostId = 4,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 62,
                            Content = "Ötekinden düşünüyor voluptatem ipsum suscipit et molestiae.",
                            PostId = 32,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 63,
                            Content = "Exercitationem alias layıkıyla göze aspernatur.",
                            PostId = 38,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 64,
                            Content = "Esse eius sarmal voluptatem et sed doğru consequatur dolorem.",
                            PostId = 11,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 65,
                            Content = "Ve ut molestiae aliquid şafak sevindi sequi camisi.",
                            PostId = 8,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 66,
                            Content = "Ki et deleniti lakin beğendim ut.",
                            PostId = 7,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 67,
                            Content = "Aliquam consequatur corporis laboriosam beatae sokaklarda mutlu filmini.",
                            PostId = 17,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 68,
                            Content = "Enim bundan iusto masaya sequi commodi ut autem yaptı.",
                            PostId = 47,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 69,
                            Content = "Quis nesciunt eaque.",
                            PostId = 31,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 70,
                            Content = "Corporis praesentium açılmadan aspernatur uzattı.",
                            PostId = 42,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 71,
                            Content = "Cezbelendi qui enim commodi dolayı sevindi nemo inventore yaptı eum.",
                            PostId = 41,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 72,
                            Content = "Ut illo öyle otobüs sokaklarda.",
                            PostId = 24,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 73,
                            Content = "Ötekinden dışarı sit commodi sit mıknatıslı.",
                            PostId = 11,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 74,
                            Content = "Beğendim cesurca dolor veniam.",
                            PostId = 22,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 75,
                            Content = "Sunt minima gitti consequatur deleniti balıkhaneye amet aut bahar adipisci.",
                            PostId = 50,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 76,
                            Content = "Işık in consequatur consectetur quis yapacakmış umut ea layıkıyla.",
                            PostId = 34,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 77,
                            Content = "Değirmeni quam aut ekşili bilgisayarı consequatur masanın.",
                            PostId = 36,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 78,
                            Content = "Uzattı türemiş gördüm.",
                            PostId = 37,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 79,
                            Content = "Sıla sokaklarda adanaya.",
                            PostId = 41,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 80,
                            Content = "Veniam rem autem gülüyorum umut sayfası sıfat quia eaque.",
                            PostId = 20,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 81,
                            Content = "Quasi beatae quis göze çünkü molestiae domates gördüm.",
                            PostId = 31,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 82,
                            Content = "Dergi odio autem.",
                            PostId = 22,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 83,
                            Content = "Aliquam öyle ipsum ipsum çobanın molestiae otobüs neque ea beatae.",
                            PostId = 8,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 84,
                            Content = "Aperiam ex ad minima amet balıkhaneye bahar aliquid enim sıfat.",
                            PostId = 25,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 85,
                            Content = "Sandalye modi laudantium çıktılar non ipsa değirmeni deleniti fugit de.",
                            PostId = 29,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 86,
                            Content = "Anlamsız aliquid gidecekmiş ut.",
                            PostId = 22,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 87,
                            Content = "Ducimus incidunt ea telefonu odio okuma ut kulu voluptatem sequi.",
                            PostId = 23,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 88,
                            Content = "Çorba alias dolorem non beğendim ama ducimus.",
                            PostId = 46,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 89,
                            Content = "Şafak quae lambadaki beğendim mutlu duyulmamış magni et voluptatem orta.",
                            PostId = 34,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 90,
                            Content = "Ex balıkhaneye nostrum anlamsız ona ut.",
                            PostId = 34,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 91,
                            Content = "Mutlu autem şafak sunt rem.",
                            PostId = 49,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 92,
                            Content = "Architecto kulu illo.",
                            PostId = 43,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 93,
                            Content = "Quasi ducimus dicta sevindi ut velit voluptatem tv göze.",
                            PostId = 32,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 94,
                            Content = "Aspernatur exercitationem lambadaki sinema için ea quia orta adipisci.",
                            PostId = 15,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 95,
                            Content = "Qui vitae teldeki ratione koyun koyun lambadaki.",
                            PostId = 4,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 96,
                            Content = "Mıknatıslı ve vel in reprehenderit.",
                            PostId = 40,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 97,
                            Content = "Türemiş eos ki quia gitti tempora camisi.",
                            PostId = 43,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 98,
                            Content = "Sit sit doğru velit tempora layıkıyla çorba ab laudantium.",
                            PostId = 18,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 99,
                            Content = "Öyle sokaklarda sinema.",
                            PostId = 13,
                            UserId = 0
                        },
                        new
                        {
                            CommentId = 100,
                            Content = "Batarya çarpan ab oldular in eve bahar balıkhaneye türemiş.",
                            PostId = 18,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Description = "Rem non bilgiyasayarı exercitationem non aliquam ipsum. Corporis illo sed aperiam sunt. Consectetur dışarı dolorem dolayı çorba un ducimus açılmadan otobüs alias. Bilgiyasayarı aut olduğu bilgisayarı.",
                            Title = "Voluptatum aut nihil illo camisi karşıdakine sit sed rem.",
                            UserId = 4
                        },
                        new
                        {
                            PostId = 2,
                            Description = "Voluptatem adresini sarmal göze sayfası layıkıyla. Sequi kalemi gülüyorum patlıcan dışarı quia. Aspernatur magni consequuntur ad. Doloremque ekşili architecto gidecekmiş düşünüyor totam magnam.",
                            Title = "İusto quam koyun vitae molestiae yapacakmış kulu.",
                            UserId = 6
                        },
                        new
                        {
                            PostId = 3,
                            Description = "Ona aut masaya aliquid sokaklarda ki voluptas iusto. Anlamsız mutlu makinesi öyle quia enim iusto beğendim. Corporis nisi eve ve sokaklarda dignissimos yapacakmış.",
                            Title = "Beğendim et nihil ona.",
                            UserId = 6
                        },
                        new
                        {
                            PostId = 4,
                            Description = "Magni aliquam sequi bundan sit ve quia ışık gitti amet. Consequatur dolayı adresini ötekinden domates eaque sıla. Salladı bahar mi consequuntur aspernatur dolores. Adipisci değirmeni qui magni çıktılar salladı labore. Kapının eos autem cesurca batarya anlamsız kalemi voluptate aliquid. Laudantium consectetur voluptatem autem sıfat ipsum çarpan.",
                            Title = "Dışarı ona sed yazın aliquam çobanın çünkü.",
                            UserId = 9
                        },
                        new
                        {
                            PostId = 5,
                            Description = "Eve illo aut dicta masanın sed mi quis explicabo. Mi consequatur sit. Dışarı totam sed nihil voluptatem ullam aliquam. Beğendim sayfası accusantium quia sıla. Consequatur voluptatem beatae çakıl eaque sequi sit beğendim masanın.",
                            Title = "İn aut sunt masanın camisi suscipit un.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 6,
                            Description = "Kapının ekşili eaque. Sevindi enim filmini nihil gördüm adanaya camisi mutlu kapının koşuyorlar. Quaerat quia iure ducimus değirmeni. Ex laboriosam de ama quia ducimus ve sıla sevindi.",
                            Title = "Dağılımı suscipit et teldeki ki nisi ki.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 7,
                            Description = "Magnam fugit labore cezbelendi doğru cesurca batarya vel quia lakin. Dicta iusto çorba sevindi çıktılar. Mutlu beğendim doloremque neque nemo sit. Odio velit et minima çorba corporis filmini ama. Odio dağılımı aut sokaklarda velit sit nostrum koştum modi gazete.",
                            Title = "Odit çorba consequatur duyulmamış hesap.",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 8,
                            Description = "Patlıcan dağılımı mutlu ipsum şafak tempora corporis masanın esse. Deleniti iusto enim camisi voluptas inventore aut. Quam bahar nemo ipsam. Masanın explicabo ama karşıdakine nisi. Düşünüyor ullam quia. Tempora için alias eaque adanaya.",
                            Title = "Adipisci et ekşili kapının blanditiis dignissimos iusto laudantium lambadaki okuma.",
                            UserId = 9
                        },
                        new
                        {
                            PostId = 9,
                            Description = "Uzattı inventore odio sevindi iusto kutusu teldeki voluptatum quae odio. Eaque enim kapının. Mi iusto uzattı patlıcan ama şafak nihil nisi. Nisi çıktılar sequi balıkhaneye sit mıknatıslı tempora sit patlıcan consequatur.",
                            Title = "Sed quis qui yazın quasi ışık consequuntur in ki düşünüyor.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 10,
                            Description = "Çorba aut dicta dignissimos ut. Deleniti illo alias velit patlıcan gazete. Aut enim gördüm dışarı göze adresini voluptatem molestiae. Autem türemiş filmini.",
                            Title = "Enim qui quae mıknatıslı salladı suscipit quae nesciunt voluptatem.",
                            UserId = 9
                        },
                        new
                        {
                            PostId = 11,
                            Description = "Beğendim odio koştum patlıcan koyun. Gitti aliquam architecto ut quaerat mıknatıslı consectetur sandalye ötekinden. Gülüyorum mutlu layıkıyla eius çarpan ea. Modi dolorem esse doğru sit ea gülüyorum quia olduğu deleniti. Aliquid sıfat gördüm consequatur fugit gidecekmiş veniam explicabo veritatis öyle. Salladı velit adanaya sit modi kulu magni koyun orta değirmeni.",
                            Title = "Cesurca sed düşünüyor bilgiyasayarı olduğu cesurca quam consequatur.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 12,
                            Description = "Suscipit et molestiae nesciunt okuma exercitationem alias layıkıyla. Aspernatur ad sit esse. Sarmal voluptatem et sed doğru consequatur dolorem karşıdakine. Ve ut molestiae aliquid şafak sevindi sequi camisi. Consequatur ki et deleniti. Beğendim ut ki numquam.",
                            Title = "Vitae ötekinden düşünüyor.",
                            UserId = 8
                        },
                        new
                        {
                            PostId = 13,
                            Description = "Enim bundan iusto masaya sequi commodi ut autem yaptı. Değirmeni quis nesciunt eaque voluptatem gazete corporis praesentium açılmadan aspernatur. Sit autem cezbelendi qui enim commodi. Sevindi nemo inventore yaptı eum voluptatem.",
                            Title = "Corporis laboriosam beatae sokaklarda mutlu filmini.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 14,
                            Description = "Sit mıknatıslı sevindi lambadaki beğendim cesurca dolor veniam domates. Sunt minima gitti consequatur deleniti balıkhaneye amet aut bahar adipisci. Voluptatem ışık in consequatur consectetur quis yapacakmış umut ea layıkıyla. Et değirmeni quam aut ekşili bilgisayarı consequatur masanın. Olduğu uzattı türemiş gördüm aliquam patlıcan sıla sokaklarda.",
                            Title = "İllo öyle otobüs sokaklarda accusantium voluptatem ötekinden dışarı.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 15,
                            Description = "Numquam quasi beatae quis göze çünkü. Domates gördüm eos çobanın dergi odio autem düşünüyor nihil aliquam. İpsum ipsum çobanın molestiae. Neque ea beatae.",
                            Title = "Voluptatem veniam rem autem gülüyorum umut sayfası sıfat quia.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 16,
                            Description = "Sandalye modi laudantium çıktılar non ipsa değirmeni deleniti fugit de. Gördüm anlamsız aliquid gidecekmiş ut bahar qui. İncidunt ea telefonu odio okuma ut kulu voluptatem sequi consequatur. Çorba alias dolorem non beğendim ama ducimus.",
                            Title = "Aperiam ex ad minima amet balıkhaneye bahar aliquid enim sıfat.",
                            UserId = 10
                        },
                        new
                        {
                            PostId = 17,
                            Description = "Ex balıkhaneye nostrum anlamsız ona ut. Kulu mutlu autem şafak sunt rem praesentium çobanın. Kulu illo ut ullam quasi ducimus dicta. Ut velit voluptatem tv. Nesciunt ipsam aspernatur exercitationem.",
                            Title = "Şafak quae lambadaki beğendim mutlu duyulmamış magni et voluptatem orta.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 18,
                            Description = "Qui vitae teldeki ratione koyun koyun lambadaki. Gazete mıknatıslı ve. İn reprehenderit exercitationem odit türemiş eos ki quia gitti tempora. Ex ad sit.",
                            Title = "İçin ea quia orta adipisci.",
                            UserId = 7
                        },
                        new
                        {
                            PostId = 19,
                            Description = "Laudantium kapının masaya öyle sokaklarda sinema eve. Batarya çarpan ab oldular in eve bahar balıkhaneye türemiş. Perferendis vitae quia düşünüyor qui.",
                            Title = "Velit tempora layıkıyla.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 20,
                            Description = "Commodi filmini uzattı esse dicta exercitationem düşünüyor çakıl. Quis quis esse aut odit. Ea aut dağılımı sed ötekinden kapının totam. Ex vitae consequatur architecto qui duyulmamış ullam explicabo.",
                            Title = "Aliquid architecto tempora masanın.",
                            UserId = 8
                        },
                        new
                        {
                            PostId = 21,
                            Description = "Consequatur veritatis alias ea ut rem dignissimos accusantium. Telefonu hesap vel kalemi quasi ötekinden. Çarpan vitae consequatur.",
                            Title = "Sed ipsum sandalye quasi balıkhaneye autem sunt ex çıktılar.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 22,
                            Description = "Kulu ki quasi de. Praesentium totam tv doğru sequi batarya sandalye suscipit yazın. Veniam yapacakmış ad iure. İusto exercitationem sıfat.",
                            Title = "Salladı sokaklarda quis esse sevindi.",
                            UserId = 4
                        },
                        new
                        {
                            PostId = 23,
                            Description = "Dolor ut çobanın oldular eaque cezbelendi çünkü. Vitae koyun layıkıyla neque koyun aut. Koşuyorlar voluptatem cesurca qui gördüm hesap mutlu sıfat. Laboriosam bilgiyasayarı voluptatem sokaklarda neque çorba dolor. Dolorem sed quia olduğu dignissimos qui. Teldeki numquam perferendis sit consequuntur.",
                            Title = "Velit oldular voluptatem uzattı aut.",
                            UserId = 7
                        },
                        new
                        {
                            PostId = 24,
                            Description = "Bahar explicabo illo ona yaptı. Nemo cesurca tempora sit deleniti sed esse aspernatur türemiş ea. Quasi accusantium commodi.",
                            Title = "Ducimus ad masaya gül deleniti gülüyorum qui voluptas.",
                            UserId = 9
                        },
                        new
                        {
                            PostId = 25,
                            Description = "Ab makinesi non kalemi açılmadan doğru labore enim amet. Vel anlamsız consectetur. Nisi alias ipsam teldeki nihil. Beğendim sinema alias labore sed balıkhaneye.",
                            Title = "Quis çorba çarpan mi ki beatae cezbelendi dolorem.",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 26,
                            Description = "Dolores consequatur eum veritatis. İpsam labore çıktılar. Quia laboriosam illo blanditiis bilgiyasayarı quia dolore layıkıyla tempora.",
                            Title = "Enim yapacakmış kutusu çünkü kutusu.",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 27,
                            Description = "Açılmadan voluptate voluptatem aliquid eaque değerli koştum sed esse odit. Nesciunt nesciunt olduğu velit qui ut voluptas salladı değerli. Beatae gül yaptı. İncidunt rem ut qui.",
                            Title = "Kutusu vel qui et camisi laudantium.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 28,
                            Description = "Ea blanditiis gitti. Et aliquid adresini nisi çünkü bilgiyasayarı camisi vel koşuyorlar. Türemiş laboriosam commodi voluptas alias numquam nostrum çobanın quasi quia. İçin enim ve commodi sayfası voluptatem reprehenderit ea nemo. Adanaya telefonu dolore aut. Enim consequatur voluptate ab laboriosam ona bilgiyasayarı.",
                            Title = "Otobüs sıradanlıktan minima enim ea doğru.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 29,
                            Description = "Koşuyorlar aliquam layıkıyla bahar filmini. Gül batarya laudantium ad açılmadan ekşili. Layıkıyla labore de. Ki göze quam molestiae ea karşıdakine tv ut aperiam. Fugit otobüs molestiae gazete quis mutlu aut aspernatur sit eius.",
                            Title = "Quam et anlamsız.",
                            UserId = 6
                        },
                        new
                        {
                            PostId = 30,
                            Description = "Blanditiis gitti ipsam ullam neque kulu. Architecto ama fugit aspernatur ipsa. Umut anlamsız sarmal voluptatem laboriosam consequatur vel. Alias dağılımı layıkıyla umut inventore. Tv bilgisayarı velit batarya dağılımı. İçin öyle suscipit aut.",
                            Title = "Ekşili ama fugit eum çakıl değerli consectetur eve.",
                            UserId = 10
                        },
                        new
                        {
                            PostId = 31,
                            Description = "Minima eaque suscipit ipsam vel karşıdakine quasi quis yaptı. Çobanın rem okuma doloremque ab sarmal balıkhaneye kapının. Odio karşıdakine sit neque ki sıla. Hesap ekşili sevindi okuma sıradanlıktan eos consequatur çorba.",
                            Title = "Sevindi ışık nihil ona telefonu ki velit in.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 32,
                            Description = "Sed dağılımı velit consequatur nostrum. Enim hesap ab vitae ipsum molestiae ex. Aut ışık vel kulu amet salladı sandalye veritatis.",
                            Title = "Kulu ama yapacakmış ea eos ducimus.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 33,
                            Description = "Kapının göze dolorem kulu explicabo doğru. Consequatur sarmal consequuntur illo teldeki gitti makinesi beatae. Fugit sit ut değirmeni tv.",
                            Title = "Lakin çünkü anlamsız ea.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 34,
                            Description = "Quia iure dağılımı doğru lakin sarmal mıknatıslı ab. Odit aperiam telefonu qui. Sunt sevindi sıradanlıktan. Magni ut ipsa ötekinden orta bilgisayarı sit otobüs odio.",
                            Title = "Sokaklarda laudantium orta değerli exercitationem.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 35,
                            Description = "Ex gül sokaklarda de mi yazın veritatis. Explicabo gülüyorum duyulmamış ışık quia. Dolor sayfası kutusu şafak bilgiyasayarı çıktılar suscipit cezbelendi dicta.",
                            Title = "Eaque qui dignissimos qui quia.",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 36,
                            Description = "Molestiae koyun sinema. Consequatur corporis ama consequatur exercitationem ab aut voluptatem. Voluptate qui nisi quia minima lakin voluptatem enim. Sed explicabo anlamsız tempora göze odio commodi qui patlıcan.",
                            Title = "Enim öyle dolor adipisci architecto kalemi.",
                            UserId = 7
                        },
                        new
                        {
                            PostId = 37,
                            Description = "Aliquam sequi corporis mutlu filmini velit layıkıyla ona. Eum veritatis voluptatem umut minima bilgiyasayarı voluptatem gidecekmiş. Sed ad voluptatem quaerat. Voluptatem masaya çorba aperiam ut voluptatem odit.",
                            Title = "Çakıl dolor sıradanlıktan.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 38,
                            Description = "Quaerat doğru sit enim voluptatum koyun. Bilgisayarı architecto eve açılmadan kutusu eum. Dolore aut anlamsız deleniti yazın makinesi. Quis lakin koşuyorlar voluptatem de. Sinema okuma masanın aliquam ipsum sokaklarda enim.",
                            Title = "Ab quam tv aut.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 39,
                            Description = "Sed minima voluptatem nihil iure un quae. Ki consequatur quia ışık türemiş. Aliquam için quaerat uzattı veritatis enim bilgisayarı teldeki layıkıyla. Biber cezbelendi göze.",
                            Title = "Sandalye ea ut kutusu değirmeni iusto quia ışık.",
                            UserId = 9
                        },
                        new
                        {
                            PostId = 40,
                            Description = "Ut uzattı eve incidunt de exercitationem velit vitae ex. Odit in consequatur. Çıktılar biber incidunt numquam odit magni velit şafak amet ut. Qui orta quaerat quia ex domates layıkıyla ötekinden vel.",
                            Title = "Dolayı ışık qui ullam ut.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 41,
                            Description = "Dışarı qui beğendim düşünüyor. Batarya dignissimos çarpan otobüs dergi. Batarya bundan labore dicta nihil vitae labore quam reprehenderit. Quia öyle quasi. Quia laboriosam masanın ea umut sandalye batarya.",
                            Title = "İçin enim ratione biber şafak.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 42,
                            Description = "Non eos balıkhaneye ekşili illo eius ut. Fugit quis yazın sunt aperiam sit çıktılar explicabo. Voluptas consequatur dolore beğendim ipsam beğendim. Laudantium numquam salladı. Yapacakmış düşünüyor ipsa yaptı.",
                            Title = "Perferendis değerli düşünüyor ekşili.",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 43,
                            Description = "Lakin fugit anlamsız masaya voluptatem eius voluptatem gülüyorum in. Voluptatem sandalye qui sevindi vel eve sayfası. Quia ipsum nesciunt dolayı. Uzattı tempora et için. Enim koşuyorlar quasi ipsam deleniti quam. Dağılımı okuma telefonu dağılımı.",
                            Title = "Bilgiyasayarı adresini sayfası dignissimos telefonu.",
                            UserId = 10
                        },
                        new
                        {
                            PostId = 44,
                            Description = "Deleniti minima dışarı dağılımı. Enim düşünüyor amet sandalye. Fugit tv bilgiyasayarı consectetur. Voluptatem sandalye değirmeni.",
                            Title = "Karşıdakine kulu voluptatem autem çünkü camisi masanın.",
                            UserId = 1
                        },
                        new
                        {
                            PostId = 45,
                            Description = "Aut blanditiis olduğu amet koşuyorlar enim qui veniam. Kapının ullam quia labore deleniti ama aut voluptatum non. Orta quis un layıkıyla sed kutusu modi enim. Çorba voluptatem veniam için lambadaki. Quis qui ea sunt ama mutlu çıktılar quasi.",
                            Title = "Odio sandalye ducimus voluptas bilgisayarı bahar değirmeni hesap.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 46,
                            Description = "Ea bahar autem düşünüyor accusantium dicta. Koştum magni gülüyorum sed velit eaque bilgisayarı ışık ipsam sit. Biber uzattı commodi göze ut ötekinden. Autem çobanın nisi qui non sinema bahar inventore et. Kapının magnam accusantium çünkü quis ötekinden qui nihil biber.",
                            Title = "Ea okuma fugit qui kalemi eaque bundan beğendim.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 47,
                            Description = "Yazın ışık aut qui adipisci quae ratione magni ama olduğu. Ea numquam çakıl gördüm minima. Quis yazın cezbelendi gazete. Deleniti qui sinema aperiam çarpan neque. Dolores otobüs yaptı. Mutlu kapının duyulmamış masanın dışarı sed sıla ea doloremque.",
                            Title = "Voluptas quasi aliquam dolores.",
                            UserId = 5
                        },
                        new
                        {
                            PostId = 48,
                            Description = "Consequatur et sit qui quia. Velit sıfat kutusu koşuyorlar. Vitae voluptas gülüyorum in salladı kulu ipsam autem ratione bilgisayarı.",
                            Title = "Numquam tv fugit praesentium tv.",
                            UserId = 2
                        },
                        new
                        {
                            PostId = 49,
                            Description = "Sıla aliquid lakin et adipisci. Accusantium qui ipsa. Autem molestiae neque eve ullam qui ışık gördüm de layıkıyla.",
                            Title = "Hesap reprehenderit et et karşıdakine sıfat in ona qui.",
                            UserId = 3
                        },
                        new
                        {
                            PostId = 50,
                            Description = "Vitae quae quis salladı commodi. Adanaya voluptas adanaya masanın modi aliquid layıkıyla dignissimos. Sit ama makinesi quia olduğu. Aspernatur otobüs aut ekşili ea gülüyorum. Sunt doğru qui bilgiyasayarı tv illo adresini sokaklarda aperiam dolore. Magni tv hesap.",
                            Title = "Sed mutlu ut aliquam illo voluptatem masaya ona.",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Buzaçtutuk Öztonga",
                            Position = "Customer Factors Analyst"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Akdoğan Baykam",
                            Position = "Dynamic Intranet Strategist"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Atıla Koç",
                            Position = "Principal Quality Manager"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Bürküt Sadıklar",
                            Position = "Legacy Web Specialist"
                        },
                        new
                        {
                            UserId = 5,
                            Name = "Çablı Korol",
                            Position = "Dynamic Applications Designer"
                        },
                        new
                        {
                            UserId = 6,
                            Name = "Gelincik Pektemek",
                            Position = "Dynamic Web Coordinator"
                        },
                        new
                        {
                            UserId = 7,
                            Name = "Altmışkara Adıvar",
                            Position = "Principal Markets Executive"
                        },
                        new
                        {
                            UserId = 8,
                            Name = "Basar Berberoğlu",
                            Position = "Dynamic Intranet Executive"
                        },
                        new
                        {
                            UserId = 9,
                            Name = "Akbaş Erez",
                            Position = "Global Usability Representative"
                        },
                        new
                        {
                            UserId = 10,
                            Name = "Bağatur Kumcuoğlu",
                            Position = "Chief Functionality Director"
                        });
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
